name: assets_dialogbottomsheet_navgator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_colorpicker: ^1.0.3
  flutter_picker: ^2.1.0
  intl: ^0.19.0
  open_file: ^3.3.2
  provider: ^6.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true
